spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/tmax_rookie?serverTimezone=UTC&characterEncoding=UTF-8
    username: soohyuk96
    password: hyukis1216
    mybatis:
      mapper-locations: classpath:/mybatis/**/sql-*.xml